title: Saeedeh Moghimi
description: > # this means to ignore newlines until "baseurl:"
  Saeedeh Moghimi's Weblog, you can call me Hedeesa:)
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://saeedehmoghimi.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Saeedeh Moghimi # add your name
author-img: Saeedeh.jpg # add your photo
about-author: I am DevOps Engineer. Currently, Working in Cafebazaar. This is my weblog to share some of my documents with you. Feel free to contact me, You can find me by the name of Hedeesa anywhere:) # add description
social-twitter: hedeesaa # add your Twitter handle
social-instagram: hedeesaa # add your Instagram handle
social-github: hedeesaa # add your Github handle
social-linkedin: SaeedehMoghimi # add your Linkedin handle
social-email: moghimi.saeedeh@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
